import { Excuse } from './types';

export const EXCUSES: Excuse[] = [
  // Tech (20 items)
  { id: 't1', text: "My VPN glitched into a parallel universe—WFH to debug reality.", category: 'tech', icon: '🌐' },
  { id: 't2', text: "Router rebellion: It's holding my cat's Zoom meeting hostage.", category: 'tech', icon: '📶' },
  { id: 't3', text: "Code merged with existential dread overnight—need home setup to revert.", category: 'tech', icon: '💻' },
  { id: 't4', text: "Waiting for the node_modules folder to finish installing gravity.", category: 'tech', icon: '📦' },
  { id: 't5', text: "My firewall is blocking physical interaction today.", category: 'tech', icon: '🛡️' },
  { id: 't6', text: "My keyboard has declared independence and refuses to travel.", category: 'tech', icon: '⌨️' },
  { id: 't7', text: "Cloud provider outage grounded my motivation to commute.", category: 'tech', icon: '☁️' },
  { id: 't8', text: "Debugging a race condition in my morning coffee routine.", category: 'tech', icon: '☕' },
  { id: 't9', text: "My IDE decided to re-index the entire internet, CPU at 100%.", category: 'tech', icon: '💾' },
  { id: 't10', text: "Git conflict with reality: HEAD detached from body.", category: 'tech', icon: '🐙' },
  { id: 't11', text: "Docker container escaped and is hiding in the fridge.", category: 'tech', icon: '🐳' },
  { id: 't12', text: "My RAM forgot everything, including my desire to commute.", category: 'tech', icon: '🧠' },
  { id: 't13', text: "Suffering from a kernel panic in my morning routine.", category: 'tech', icon: '⚠️' },
  { id: 't14', text: "Localhost refused to connect to my productivity.", category: 'tech', icon: '🚫' },
  { id: 't15', text: "My wifi is having a mid-life crisis and demands a sabbatical.", category: 'tech', icon: '📡' },
  { id: 't16', text: "CSS grid misalignment caused structural instability in my apartment.", category: 'tech', icon: '🏗️' },
  { id: 't17', text: "Blue Screen of Death appeared on my smart toaster.", category: 'tech', icon: '🍞' },
  { id: 't18', text: "Stack Overflow is down, so I am functionally incapacitated.", category: 'tech', icon: '🔽' },
  { id: 't19', text: "My 2FA token generated a number that doesn't exist.", category: 'tech', icon: '🔢' },
  { id: 't20', text: "Deploying a hotfix to my sleep schedule.", category: 'tech', icon: '💤' },

  // Pet (20 items)
  { id: 'p1', text: "Pet quantum entangled with keyboard; office unsafe until Schrödinger checks.", category: 'pet', icon: '🐱' },
  { id: 'p2', text: "Dog ate my motivation and is currently digesting it on the rug.", category: 'pet', icon: '🐕' },
  { id: 'p3', text: "Cat is sleeping on my legs. Legally, I cannot move.", category: 'pet', icon: '🐈' },
  { id: 'p4', text: "My iguana is having an identity crisis and needs emotional support.", category: 'pet', icon: '🦎' },
  { id: 'p5', text: "My dog scheduled a mandatory 1:1 cuddle session.", category: 'pet', icon: '🦴' },
  { id: 'p6', text: "Cat is debugging my keyboard by sitting on 'Delete'.", category: 'pet', icon: '😼' },
  { id: 'p7', text: "Goldfish looks lonely, need to provide moral support.", category: 'pet', icon: '🐠' },
  { id: 'p8', text: "Parrot is leaking sensitive company data to the neighbors.", category: 'pet', icon: '🦜' },
  { id: 'p9', text: "Hamster wheel generated excess static, interfering with Zoom.", category: 'pet', icon: '🐹' },
  { id: 'p10', text: "My cat is currently downloading a software update (sleeping).", category: 'pet', icon: '💤' },
  { id: 'p11', text: "Dog hid my car keys in a location known only to the elder gods.", category: 'pet', icon: '🗝️' },
  { id: 'p12', text: "My turtle is rushing me, but I can't keep up with his pace.", category: 'pet', icon: '🐢' },
  { id: 'p13', text: "Cat threw up a hairball on the router. Connectivity compromise.", category: 'pet', icon: '🤮' },
  { id: 'p14', text: "My rabbit ate the internet cable. Again.", category: 'pet', icon: '🐇' },
  { id: 'p15', text: "Dog thinks the webcam is an enemy combatant.", category: 'pet', icon: '📹' },
  { id: 'p16', text: "Cat has trapped me in the bathroom. Send help (or snacks).", category: 'pet', icon: '🚪' },
  { id: 'p17', text: "Dog is judging my outfit, need to change (takes all day).", category: 'pet', icon: '👔' },
  { id: 'p18', text: "My lizard is cold and requires body heat application.", category: 'pet', icon: '🌡️' },
  { id: 'p19', text: "My bird is trying to type a novel on my laptop.", category: 'pet', icon: '🦅' },
  { id: 'p20', text: "The neighbor's cat looked at me weird and I'm scared to leave.", category: 'pet', icon: '👀' },

  // Absurd (20 items)
  { id: 'a1', text: "Mercury is in retrograde and my car knows it.", category: 'absurd', icon: '🪐' },
  { id: 'a2', text: "I looked outside and the vibes were off.", category: 'absurd', icon: '🔮' },
  { id: 'a3', text: "Currently negotiating a peace treaty with my alarm clock.", category: 'absurd', icon: '⏰' },
  { id: 'a4', text: "The floor is lava. Literally. It's a whole thing.", category: 'absurd', icon: '🌋' },
  { id: 'a5', text: "I stepped on a Lego and need 24 hours to recover spiritually.", category: 'absurd', icon: '🧱' },
  { id: 'a6', text: "The stars aligned in a way that prohibits spreadsheets.", category: 'absurd', icon: '✨' },
  { id: 'a7', text: "I accidentally joined a cult while making toast.", category: 'absurd', icon: '🍞' },
  { id: 'a8', text: "My horoscope said 'Stay put' and I don't argue with space.", category: 'absurd', icon: '🌌' },
  { id: 'a9', text: "A wizard blocked my driveway with a magical barrier.", category: 'absurd', icon: '🧙‍♂️' },
  { id: 'a10', text: "I’m currently existing in a non-Euclidean geometry.", category: 'absurd', icon: '📐' },
  { id: 'a11', text: "Time loop. I've already attended this meeting tomorrow.", category: 'absurd', icon: '⏳' },
  { id: 'a12', text: "My shadow refused to follow me out the door.", category: 'absurd', icon: '👤' },
  { id: 'a13', text: "The vibe check failed critical diagnostics.", category: 'absurd', icon: '📉' },
  { id: 'a14', text: "Gravity is significantly stronger in my bedroom today.", category: 'absurd', icon: '🪨' },
  { id: 'a15', text: "I suspect my house is haunted by a lazy ghost.", category: 'absurd', icon: '👻' },
  { id: 'a16', text: "Aliens abducted my motivation, negotiating its return.", category: 'absurd', icon: '👽' },
  { id: 'a17', text: "The simulation is glitching; textures outside haven't loaded.", category: 'absurd', icon: '👾' },
  { id: 'a18', text: "My fortune cookie said 'Work from home', legally binding.", category: 'absurd', icon: '🥠' },
  { id: 'a19', text: "I'm training for a marathon (on Netflix).", category: 'absurd', icon: '📺' },
  { id: 'a20', text: "The birds outside are singing too loudly to concentrate in office.", category: 'absurd', icon: '🐦' },

  // Health/Human (33 items)
  { id: 'h1', text: "Allergic to fluorescent lighting today.", category: 'health', icon: '💡' },
  { id: 'h2', text: "My social battery is at 1% and I can't find the dongle.", category: 'health', icon: '🔋' },
  { id: 'h3', text: "Suffering from acute lack-of-commute-desire syndrome.", category: 'health', icon: '🚗' },
  { id: 'h4', text: "My circadian rhythm is playing jazz improv.", category: 'health', icon: '🎷' },
  { id: 'h5', text: "Suffering from severe coffee deficiency.", category: 'health', icon: '☕' },
  { id: 'h6', text: "I have a case of the Mondays, specifically the acute variant.", category: 'health', icon: '📅' },
  { id: 'h7', text: "My aura needs a recharge.", category: 'health', icon: '🧘' },
  { id: 'h8', text: "Brain.exe has stopped responding.", category: 'health', icon: '🤯' },
  { id: 'h9', text: "I'm allergic to putting on real pants today.", category: 'health', icon: '👖' },
  { id: 'h10', text: "My introvert levels are critically high.", category: 'health', icon: '😶' },
  { id: 'h11', text: "Detected a disturbance in the force (my stomach).", category: 'health', icon: '🤢' },
  { id: 'h12', text: "Psychologically incompatible with traffic right now.", category: 'health', icon: '🚦' },
  { id: 'h13', text: "My spirit animal is a sloth today.", category: 'health', icon: '🦥' },
  { id: 'h14', text: "I need to defragment my mental hard drive.", category: 'health', icon: '🧩' },
  { id: 'h15', text: "Currently operating in safe mode.", category: 'health', icon: '🛡️' },
  { id: 'h16', text: "Running low on serotonin, recharging at home base.", category: 'health', icon: '🔋' },
  { id: 'h17', text: "My patience buffer overflowed.", category: 'health', icon: '😤' },
  { id: 'h18', text: "I have a meeting with my pillow regarding previous performance.", category: 'health', icon: '🛌' },
  { id: 'h19', text: "Experiencing technical difficulties with my personality.", category: 'health', icon: '🎭' },
  { id: 'h20', text: "My chakras are misaligned, causing network latency.", category: 'health', icon: '🕉️' },
  { id: 'h21', text: "I'm too photogenic for the office lighting today.", category: 'health', icon: '📸' },
  { id: 'h22', text: "Navigating a complex emotional landscape (I spilled my tea).", category: 'health', icon: '🍵' },
  { id: 'h23', text: "My inner child refuses to get in the car.", category: 'health', icon: '👶' },
  { id: 'h24', text: "Suffering from excessive comfort syndrome.", category: 'health', icon: '🛋️' },
  { id: 'h25', text: "I blinked and now it's afternoon.", category: 'health', icon: '👁️' },
  { id: 'h26', text: "Hibernation instincts kicked in early.", category: 'health', icon: '🐻' },
  { id: 'h27', text: "I'm on a strictly 'no people' diet today.", category: 'health', icon: '🚫' },
  { id: 'h28', text: "My voice box is undergoing scheduled maintenance.", category: 'health', icon: '🙊' },
  { id: 'h29', text: "I have an appointment with my sanity.", category: 'health', icon: '🧠' },
  { id: 'h30', text: "Spilled coffee on my enthusiasm.", category: 'health', icon: '☕' },
  { id: 'h31', text: "My bed is hugging me and I'm not strong enough to fight back.", category: 'health', icon: '🛌' },
  { id: 'h32', text: "I'm observing a personal holiday: 'National Stay Inside Day'.", category: 'health', icon: '🗓️' },
  { id: 'h33', text: "Hair is having a bad day, cannot risk public exposure.", category: 'health', icon: '💇' },
];

export const TWITTER_INTENT_URL = "https://twitter.com/intent/tweet?text=";